# Generated by Django 2.2.19 on 2022-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220606_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='posts.Group', to_field='title'),
        ),
    ]
