# Generated by Django 2.2.16 on 2022-07-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20220717_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow',
            field=models.BooleanField(default=False, verbose_name='Статус подписки'),
        ),
    ]
