# Generated by Django 2.2.16 on 2022-07-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_follow_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
    ]
